# site settings
title: Gavin Luo
subtitle: Game Developer Portfolio
email: luoxiangyu528@gmail.com
description: Thanks for checking out my game developer portfolio. I showcase my professional game development work and personal passion projects in this portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gavinluo.com" # the base hostname & protocol for your site
author: Gavin Luo
# street_address: 1234 Somewhere Road
city: Toronto
state: Ontario
# zip_code: 55555
country: Canada
phone: (519)781-5282

# post settings
show_excerpts: true
paginate: 10
paginate_path: "/dev-logs/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sx2gavin
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/xiangyugavinluo/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown
future: true

sass:
  style: compressed
